on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

name: Upload Release Assets

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create Tar and Zip File
        run: |
          tar -czvf JuliaMono.tar.gz JuliaMono-*.ttf LICENSE
          zip JuliaMono.zip JuliaMono-*.ttf LICENSE
      - name: Upload Tar File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./JuliaMono.tar.gz
          asset_name: JuliaMono.tar.gz
          asset_content_type: application/tar+gzip
      - name: Upload Zip File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./JuliaMono.zip
          asset_name: JuliaMono.zip
          asset_content_type: application/zip
